### ISSUE TITLE
Build app with powershell scripts

### ISSUE THREAD

**Issue by dfaustryjak** [vuetifyjs/electron#14]
Hey

Can you told me how can I modify webpack. I installed and use active-window which using 
scripts wrote in powershell. 

I turn on devtools and i get this response

> 'C:\Users\user\AppData\Local\Programs\pudapp\resources\app.asar\node_modules\active-window\scripts\windows.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
