### ISSUE TITLE
Debugging electron application

### ISSUE THREAD

**Issue by lmapii** [vuetifyjs/electron#16]
First things first node.js and electron are pretty new to me so sorry for raising an issue here but I don't know where else to ask since all the boilerplates and configurations are pretty different:

Basically all I wanted to do is `console.log` within the electron application (not web), no fancy step debugging etc. So far in a normal electron application (w/o Vue) this was working using simply `console.log` and checking the terminal for output.

I've tried different configurations in VSCode which ended up not working due to ES6 syntax or webpack not serving the `index.html` (if that's what was happening), also tried navigating to `chrome://inspect/` which gives me (no surprise) pretty much the same as the command-shift-I developer tools, no luck.

Any input on how to proceed here is highly appreciated, also a how-to would be awesome.

**Edit - What I want to log is in index.js:**
```
app.on('activate', () => {
  console.log('(electron) application activated')
  if (mainWindow === null) {
    createWindow()
  }
})
```

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
