### ISSUE TITLE
Example layouts are not the same as in the web preview.

### ISSUE THREAD

**Issue by Neophen** [vuetifyjs/electron#2]
#### Example layouts work differently on web and on electron
Not sure if this is a bug.
But here's the description:
this example:
https://vuetifyjs.com/examples/layouts/baseline
Pushes the whole content to the side on web, screenshot:
<img width="1438" alt="online" src="https://user-images.githubusercontent.com/6092928/33166931-9ad0f8a2-d044-11e7-9f7e-7cec2c305a1d.png">

##### Describe the issue / bug.
When i copy paste this into your electron starter.
The navigation goes over the top but does not push the content, screenshot:
![in electron](https://user-images.githubusercontent.com/6092928/33166867-697f32aa-d044-11e7-9a7b-a79400241f00.png)
##### How can I reproduce this problem?
simply launch the electron boilerplate provided.
And copy paste the code from template into the App.vue file

##### Tell me about your development environment.
  * Node version: v8.6.0
  * NPM version: 5.5.1
  * vue-cli version: 2.9.1
  * Operating System: Mac Os Sierra 10.12.6

**Comment by nekosaur** [comment]
Using latest vuetifyjs/electron template and pasting in baseline layout it looks exactly like on docs (only major difference in setup is I'm on windows 10). If you have your project in a public repo I could take a look at it.
