### ISSUE TITLE
High risk vulnerability in dependency tree

### ISSUE THREAD

**Issue by 8bit-echo** [vuetifyjs/electron#7]
##### Issue
\# npm reports a vulnerability in the "suppose" package's dependency on "string"

##### Steps to reproduce
\# clone the repo, run npm install using node 6.x

  * Node version: 8.10.0
  * NPM version: 6.0.1
  * Operating System: macOS 10.13.4

**Comment by maurop123** [comment]
Can't reproduce this issue. Are you doing `git clone` or `vue init vuetifyjs/electron`? The latter is how it's suppose to be used.
