### ISSUE TITLE
Add vuetify to whiteListedModules

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/electron#8]
For v1.1 - see https://github.com/vuetifyjs/vuetify/issues/4068

**Comment by lcherone** [comment]
Read the linked ticket, but how is this issue fixed with electron? Is it a simple config/addition?..

Kinda annoying scrolling though all the console errors, knowing whats mine and whats related to this issue.

**Comment by KaelWD** [comment]
webpack.renderer.config.js: https://github.com/vuetifyjs/vuetify/issues/4068#issuecomment-393123259

**Comment by lcherone** [comment]
Perfect thanks @KaelWD
